// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1s5yURVVcO7KDT_y7afBq_YV6fjNeYl8',
    appId: '1:216497577766:web:3e7935442b36c8b3eaabe7',
    messagingSenderId: '216497577766',
    projectId: 'class-critique-app',
    authDomain: 'class-critique-app.firebaseapp.com',
    storageBucket: 'class-critique-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChVjtnryJNqpQYZ-aG1q5dWrk4jhj1sDM',
    appId: '1:216497577766:android:aa65c5fd14b90debeaabe7',
    messagingSenderId: '216497577766',
    projectId: 'class-critique-app',
    storageBucket: 'class-critique-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2EQw68MZXQdS8KnYCedAMMb2WbbUNO-A',
    appId: '1:216497577766:ios:4a91fd4dc0935cdceaabe7',
    messagingSenderId: '216497577766',
    projectId: 'class-critique-app',
    storageBucket: 'class-critique-app.appspot.com',
    iosBundleId: 'com.example.classCritiqueApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2EQw68MZXQdS8KnYCedAMMb2WbbUNO-A',
    appId: '1:216497577766:ios:4a91fd4dc0935cdceaabe7',
    messagingSenderId: '216497577766',
    projectId: 'class-critique-app',
    storageBucket: 'class-critique-app.appspot.com',
    iosBundleId: 'com.example.classCritiqueApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1s5yURVVcO7KDT_y7afBq_YV6fjNeYl8',
    appId: '1:216497577766:web:80f6918e8a28e050eaabe7',
    messagingSenderId: '216497577766',
    projectId: 'class-critique-app',
    authDomain: 'class-critique-app.firebaseapp.com',
    storageBucket: 'class-critique-app.appspot.com',
  );
}
